"use client";

import { Check, CircleHelp, Clock3, RefreshCw, Settings2, UserRound } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export type WorkspacePanel = { kind: "module"; name: string } | { kind: "help" | "profile" | "settings" };

export function WorkspaceDialog({ panel, onClose }: { panel: WorkspacePanel | null; onClose: () => void }) {
  const title = panel?.kind === "module" ? panel.name : panel?.kind === "help" ? "Te damos la bienvenida a Nexo" : panel?.kind === "settings" ? "Configuración del espacio" : "Perfil de demostración";
  return (
    <Dialog open={panel !== null} onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="max-h-[85dvh] overflow-y-auto p-6 sm:max-w-lg">
        <DialogHeader><DialogTitle className="text-lg">{title}</DialogTitle><DialogDescription>Nexo CRM · Espacio de demostración</DialogDescription></DialogHeader>
        {panel?.kind === "module" && <div className="py-4"><Clock3 className="mb-4 size-8 text-blue-600" /><h3 className="font-semibold">Próximamente en tu espacio de trabajo</h3><p className="mt-3 text-sm leading-relaxed text-slate-500">El módulo de {panel.name.toLowerCase()} forma parte de las siguientes etapas. Por ahora puedes explorar Resumen y gestionar tus clientes con datos locales.</p><p className="mt-4 rounded-lg bg-blue-50 p-3 text-xs leading-relaxed text-blue-800">Las oportunidades, ventas y actividades del resumen son ejemplos de la futura experiencia comercial.</p></div>}
        {panel?.kind === "help" && <div className="space-y-5 py-3 text-sm"><div className="flex gap-3"><CircleHelp className="mt-0.5 size-5 shrink-0 text-blue-600" /><div><h3 className="font-semibold">Explora tu CRM</h3><p className="mt-1 leading-relaxed text-slate-500">Resumen reúne tus indicadores. En Clientes puedes buscar, filtrar, registrar, consultar, editar y eliminar contactos.</p></div></div><div className="flex gap-3"><Check className="mt-0.5 size-5 shrink-0 text-blue-600" /><div><h3 className="font-semibold">Muévete a tu ritmo</h3><p className="mt-1 leading-relaxed text-slate-500">Usa Tab para recorrer los controles, Enter para seleccionarlos y Escape para cerrar un formulario. La búsqueda superior te lleva directamente a tus clientes.</p></div></div><div className="flex gap-3"><RefreshCw className="mt-0.5 size-5 shrink-0 text-blue-600" /><div><h3 className="font-semibold">Un espacio para probar</h3><p className="mt-1 leading-relaxed text-slate-500">Todos los datos son ficticios. Tus cambios se conservan al navegar y se reinician al recargar. La fecha de referencia es el 25 de septiembre de 2026.</p></div></div></div>}
        {panel?.kind === "settings" && <div className="py-3"><Settings2 className="mb-4 size-7 text-blue-600" /><dl className="divide-y divide-slate-100 text-sm"><div className="flex justify-between py-3"><dt className="text-slate-500">Espacio</dt><dd className="font-medium">Mi empresa</dd></div><div className="flex justify-between py-3"><dt className="text-slate-500">Idioma</dt><dd className="font-medium">Español (Perú)</dd></div><div className="flex justify-between py-3"><dt className="text-slate-500">Moneda</dt><dd className="font-medium">Sol peruano · S/</dd></div><div className="flex justify-between py-3"><dt className="text-slate-500">Almacenamiento</dt><dd className="font-medium">Memoria local</dd></div></dl><p className="mt-4 rounded-lg bg-slate-50 p-3 text-xs leading-relaxed text-slate-500">Estas preferencias describen la demostración. La configuración editable del equipo y los permisos estarán disponibles en una siguiente etapa.</p></div>}
        {panel?.kind === "profile" && <div className="py-4 text-center"><span className="mx-auto flex size-16 items-center justify-center rounded-full bg-blue-50 text-xl font-semibold text-blue-700">AG</span><h3 className="mt-4 text-lg font-semibold">Ana García</h3><p className="mt-1 text-sm text-slate-500">ana.garcia@example.com</p><p className="mt-4 inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600"><UserRound className="size-3.5" />Administrador</p><p className="mt-5 text-xs leading-relaxed text-slate-500">Perfil ficticio para explorar Nexo. La autenticación y los roles reales se incorporarán más adelante.</p></div>}
      </DialogContent>
    </Dialog>
  );
}
