"use client";
import { useEffect, useState } from "react";
import { Search, ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { responsableName } from "@/features/leads/types";
import { limaDay } from "@/features/leads/dates";
import { estimatedDate } from "@/features/opportunities/opportunity-actions";
import { formatCents, formatMoney } from "@/features/opportunities/money";
import { useSales } from "./use-sales";
import { SaleFormDialog, saleSelectStyle } from "./sale-form";
import { SaleActions, SaleStateBadge } from "./sale-actions";
import { salesStats } from "./stats";
import { PAYMENT_METHODS, SALE_STATES } from "./types";

const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
const emptyFilters = { state: "", client: "", owner: "", method: "", from: "", to: "" };
export function SalesView({ initialNow, initialOpportunityId, create = false }: { initialNow: string; initialOpportunityId?: string; create?: boolean }) {
  const { sales, directory, loading, loaded, error, reload, saved, removed } = useSales();
  const [query, setQuery] = useState("");
  const [filters, setFilters] = useState(emptyFilters);
  const [page, setPage] = useState(1);
  const [now, setNow] = useState(() => new Date(initialNow));
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 60000); return () => clearInterval(timer); }, []);
  const clientName = (id: string) => directory.clients.find((client) => client.id === id)?.name ?? "Cliente no disponible";
  const ownerName = (id: string | null) => { const person = directory.responsibles.find((owner) => owner.id === id); return person ? `${responsableName(person)}${person.activo ? "" : " (inactivo)"}` : "Sin asignar"; };
  const filtered = sales.filter((sale) => normalize(`${sale.numero} ${clientName(sale.cliente_id)} ${sale.referencia_pago}`).includes(normalize(query.trim())) && (!filters.state || sale.estado === filters.state) && (!filters.client || sale.cliente_id === filters.client) && (!filters.owner || (sale.responsable_id ?? "none") === filters.owner) && (!filters.method || (sale.metodo_pago || "none") === filters.method) && (!filters.from || sale.fecha_venta >= filters.from) && (!filters.to || sale.fecha_venta <= filters.to));
  const stats = salesStats(sales, now);
  const cards = [{ label: "Ventas totales", value: String(stats.total), detail: "Registros no cancelados · Incluye borradores" }, { label: "Ingresos pagados", value: formatCents(stats.paid), detail: "Ventas Pagadas · Histórico" }, { label: "Pendientes de pago", value: formatCents(stats.pending), detail: `${stats.pendingCount} ventas Pendientes · Excluye borradores` }, { label: "Ventas este mes", value: String(stats.month), detail: "Por fecha de venta · Excluye canceladas · Lima" }];
  const pages = Math.max(1, Math.ceil(filtered.length / 10));
  const current = Math.min(page, pages);
  function change(key: keyof typeof emptyFilters, value: string) { setFilters({ ...filters, [key]: value }); setPage(1); }
  return <div className="min-w-0 space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Ventas</h1><p className="mt-2 text-sm text-slate-500">Registra y controla tus operaciones comerciales.</p></div>{loaded ? <SaleFormDialog directory={directory} today={limaDay(now)} onSaved={(detail) => saved(detail.sale)} initialOpportunityId={initialOpportunityId} defaultOpen={create} disabled={loading || Boolean(error)} /> : <Button disabled>Nueva venta</Button>}</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <div key={card.label} className="min-w-0 rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-medium text-slate-500">{card.label}</p><p className="mt-3 break-words text-xl font-semibold">{!loaded || error ? "—" : card.value}</p><p className="mt-2 text-[11px] text-slate-500">{card.detail}</p></div>)}</div>
    <section aria-label="Listado de ventas" className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="space-y-4 border-b border-slate-100 p-4 sm:p-5"><div className="flex flex-wrap gap-3"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400" aria-hidden="true" /><Input aria-label="Buscar ventas" placeholder="Buscar por número, cliente o referencia..." value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} className="h-10 min-w-48 pl-9" /></div><Button variant="outline" disabled={loading} onClick={() => void reload()}>{loading ? "Cargando..." : "Actualizar"}</Button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <label className="space-y-1 text-xs text-slate-500">Estado<select aria-label="Filtrar por estado" value={filters.state} onChange={(event) => change("state", event.target.value)} className={saleSelectStyle}><option value="">Todos los estados</option>{SALE_STATES.map((state) => <option key={state}>{state}</option>)}</select></label>
      <label className="space-y-1 text-xs text-slate-500">Responsable<select aria-label="Filtrar por responsable" value={filters.owner} onChange={(event) => change("owner", event.target.value)} className={saleSelectStyle}><option value="">Todos los responsables</option><option value="none">Sin asignar</option>{directory.responsibles.map((person) => <option key={person.id} value={person.id}>{ownerName(person.id)}</option>)}</select></label>
      <label className="space-y-1 text-xs text-slate-500">Cliente<select aria-label="Filtrar por cliente" value={filters.client} onChange={(event) => change("client", event.target.value)} className={saleSelectStyle}><option value="">Todos los clientes</option>{directory.clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label>
      <label className="space-y-1 text-xs text-slate-500">Método de pago<select aria-label="Filtrar por método de pago" value={filters.method} onChange={(event) => change("method", event.target.value)} className={saleSelectStyle}><option value="">Todos los métodos</option><option value="none">Sin registrar</option>{PAYMENT_METHODS.map((method) => <option key={method}>{method}</option>)}</select></label>
      <label className="space-y-1 text-xs text-slate-500">Fecha desde<Input type="date" aria-label="Fecha desde" value={filters.from} onChange={(event) => change("from", event.target.value)} /></label><label className="space-y-1 text-xs text-slate-500">Fecha hasta<Input type="date" aria-label="Fecha hasta" value={filters.to} onChange={(event) => change("to", event.target.value)} /></label><Button variant="ghost" className="self-end" onClick={() => { setFilters(emptyFilters); setQuery(""); setPage(1); }}>Limpiar filtros</Button>
    </div>{filters.from && filters.to && filters.from > filters.to && <p role="alert" className="text-xs text-amber-700">La fecha inicial debe ser anterior o igual a la final.</p>}</div>
    {error ? <div role="alert" className="p-8 text-center"><p className="text-sm text-red-700">{error}</p><Button variant="outline" className="mt-4" onClick={() => void reload()}>Reintentar</Button></div> : !loaded ? <p role="status" className="p-12 text-center text-sm text-slate-500">Cargando ventas...</p> : !filtered.length ? <div className="p-12 text-center"><ShoppingBag className="mx-auto mb-3 size-8 text-slate-400" /><h2 className="font-semibold">{sales.length ? "Sin ventas para estos filtros" : "Todavía no hay ventas"}</h2><p className="mt-2 text-sm text-slate-500">{sales.length ? "Prueba otra búsqueda o limpia los filtros." : "Registra tu primera venta o créala desde una oportunidad Ganada."}</p></div> : <><Table><TableHeader><TableRow>{["Número", "Cliente", "Fecha", "Estado", "Total", "Responsable", "Método de pago", "Acciones"].map((label) => <TableHead key={label} className="px-4 text-xs">{label}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.slice((current - 1) * 10, current * 10).map((sale) => <TableRow key={sale.id}><TableCell className="px-4 py-4 font-medium">{sale.numero}</TableCell><TableCell className="max-w-48 truncate px-4 text-xs" title={clientName(sale.cliente_id)}>{clientName(sale.cliente_id)}</TableCell><TableCell className="px-4 text-xs">{estimatedDate(sale.fecha_venta)}</TableCell><TableCell className="px-4"><SaleStateBadge state={sale.estado} /></TableCell><TableCell className="px-4 text-xs font-medium">{formatMoney(sale.total)}</TableCell><TableCell className="px-4 text-xs">{ownerName(sale.responsable_id)}</TableCell><TableCell className="px-4 text-xs">{sale.metodo_pago || "Sin registrar"}</TableCell><TableCell className="px-3"><SaleActions sale={sale} directory={directory} today={limaDay(now)} onSaved={saved} onDeleted={removed} /></TableCell></TableRow>)}</TableBody></Table><div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 p-4"><p role="status" className="text-xs text-slate-500">{filtered.length} ventas · Página {current} de {pages}</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={current === 1} onClick={() => setPage(current - 1)}>Anterior</Button><Button size="sm" variant="outline" disabled={current === pages} onClick={() => setPage(current + 1)}>Siguiente</Button></div></div></>}
    </section><p className="text-xs text-slate-400">Importes en soles · Datos guardados en Supabase · Indicadores globales independientes de los filtros.</p></div>;
}
