"use client";
import { useEffect, useState } from "react";
import { GitBranch, LayoutPanelLeft, List, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { responsableName } from "@/features/leads/types";
import { useOpportunities } from "./use-opportunities";
import { OpportunityFormDialog, selectStyle } from "./opportunity-form";
import { OpportunityActions, estimatedDate } from "./opportunity-actions";
import { StageBadge, StageControl, stageColors } from "./opportunity-stage";
import { isClosed, OPPORTUNITY_STAGES, type Opportunity } from "./types";
import { formatCents, formatMoney, toCents } from "./money";
import { opportunityStats } from "./stats";

const emptyFilters = { stage: "", owner: "", client: "", status: "", from: "", to: "" };
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
export function OpportunitiesView({ initialNow, initialClientId, initialLeadId, create = false, initialSearch = "" }: { initialNow: string; initialClientId?: string; initialLeadId?: string; create?: boolean; initialSearch?: string }) {
  const { items, directory, loading, loaded, error, reload, saved, removed } = useOpportunities();
  const [view, setView] = useState<"pipeline" | "list">("pipeline");
  const [query, setQuery] = useState(initialSearch);
  const [filters, setFilters] = useState(emptyFilters);
  const [page, setPage] = useState(1);
  const [now, setNow] = useState(() => new Date(initialNow));
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 60000); return () => clearInterval(timer); }, []);
  const clientName = (id: string) => directory.clients.find((client) => client.id === id)?.name ?? "Cliente no disponible";
  const ownerName = (id: string | null) => { const owner = directory.responsibles.find((person) => person.id === id); return owner ? `${responsableName(owner)}${owner.activo ? "" : " (inactivo)"}` : "Sin asignar"; };
  const filtered = items.filter((item) => normalize(`${item.id} ${item.titulo} ${clientName(item.cliente_id)} ${item.origen}`).includes(normalize(query.trim())) && (!filters.stage || item.etapa === filters.stage) && (!filters.owner || (item.responsable_id ?? "none") === filters.owner) && (!filters.client || item.cliente_id === filters.client) && (!filters.status || isClosed(item.etapa) === (filters.status === "closed")) && (!filters.from || Boolean(item.fecha_cierre_estimada && item.fecha_cierre_estimada >= filters.from)) && (!filters.to || Boolean(item.fecha_cierre_estimada && item.fecha_cierre_estimada <= filters.to)));
  const stats = opportunityStats(items, now);
  const summary = [{ label: "Oportunidades abiertas", value: String(stats.open), detail: "Nueva, Contacto, Propuesta y Negociación" }, { label: "Valor del pipeline", value: formatCents(stats.pipeline), detail: `Ponderado: ${formatCents(stats.weighted)}` }, { label: "Ganadas este mes", value: String(stats.wonMonth), detail: "Según cierre real · Hora de Lima" }, { label: "Tasa de cierre", value: `${stats.closeRate.toLocaleString("es-PE", { maximumFractionDigits: 1 })}%`, detail: `${stats.won} ganadas / ${stats.won + stats.lost} cerradas · Histórico` }];
  const pageCount = Math.max(1, Math.ceil(filtered.length / 10));
  const currentPage = Math.min(page, pageCount);
  function changeFilter(key: keyof typeof emptyFilters, value: string) { setFilters({ ...filters, [key]: value }); setPage(1); }
  const actions = (item: Opportunity) => <OpportunityActions item={item} directory={directory} onSaved={saved} onDeleted={removed} />;
  return <div className="min-w-0 space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight text-slate-900">Oportunidades</h1><p className="mt-2 text-sm text-slate-500">Gestiona tu pipeline y convierte relaciones en ventas.</p></div>{loaded ? <OpportunityFormDialog directory={directory} onSaved={saved} initialClientId={initialClientId} initialLeadId={initialLeadId} defaultOpen={create} disabled={loading || Boolean(error)} /> : <Button disabled>Nueva oportunidad</Button>}</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{summary.map((stat) => <div key={stat.label} className="min-w-0 rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-medium text-slate-500">{stat.label}</p><p className="mt-3 break-words text-xl font-semibold tracking-tight">{!loaded || error ? "—" : stat.value}</p><p className="mt-2 text-[11px] text-slate-500">{stat.detail}</p></div>)}</div>
    <section aria-label="Filtros de oportunidades" className="space-y-4 rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex flex-wrap gap-3"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400" aria-hidden="true" /><Input className="h-10 min-w-48 pl-9" aria-label="Buscar oportunidades" placeholder="Buscar por título, cliente u origen..." value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} /></div><Button variant="outline" disabled={loading} onClick={() => void reload()}>{loading ? "Cargando..." : "Actualizar"}</Button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <label className="space-y-1 text-xs text-slate-500">Etapa<select aria-label="Filtrar por etapa" className={selectStyle} value={filters.stage} onChange={(event) => changeFilter("stage", event.target.value)}><option value="">Todas las etapas</option>{OPPORTUNITY_STAGES.map((stage) => <option key={stage}>{stage}</option>)}</select></label>
      <label className="space-y-1 text-xs text-slate-500">Responsable<select aria-label="Filtrar por responsable" className={selectStyle} value={filters.owner} onChange={(event) => changeFilter("owner", event.target.value)}><option value="">Todos los responsables</option><option value="none">Sin asignar</option>{directory.responsibles.map((person) => <option key={person.id} value={person.id}>{ownerName(person.id)}</option>)}</select></label>
      <label className="space-y-1 text-xs text-slate-500">Cliente<select aria-label="Filtrar por cliente" className={selectStyle} value={filters.client} onChange={(event) => changeFilter("client", event.target.value)}><option value="">Todos los clientes</option>{directory.clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label>
      <label className="space-y-1 text-xs text-slate-500">Estado<select aria-label="Filtrar por estado" className={selectStyle} value={filters.status} onChange={(event) => changeFilter("status", event.target.value)}><option value="">Abiertas y cerradas</option><option value="open">Abiertas</option><option value="closed">Cerradas</option></select></label>
      <label className="space-y-1 text-xs text-slate-500">Cierre estimado desde<Input aria-label="Cierre estimado desde" type="date" value={filters.from} onChange={(event) => changeFilter("from", event.target.value)} /></label><label className="space-y-1 text-xs text-slate-500">Cierre estimado hasta<Input aria-label="Cierre estimado hasta" type="date" value={filters.to} onChange={(event) => changeFilter("to", event.target.value)} /></label><Button variant="ghost" className="self-end" onClick={() => { setQuery(""); setFilters(emptyFilters); setPage(1); }}>Limpiar filtros</Button>
    </div>{filters.from && filters.to && filters.from > filters.to && <p role="alert" className="text-xs text-amber-700">La fecha inicial debe ser anterior o igual a la final.</p>}</section>
    <div className="flex flex-wrap items-center justify-between gap-3"><div role="group" aria-label="Vista de oportunidades" className="flex gap-1 rounded-lg border border-slate-200 bg-white p-1"><Button variant={view === "pipeline" ? "default" : "ghost"} size="sm" aria-pressed={view === "pipeline"} onClick={() => setView("pipeline")}><LayoutPanelLeft className="size-4" />Pipeline</Button><Button variant={view === "list" ? "default" : "ghost"} size="sm" aria-pressed={view === "list"} onClick={() => setView("list")}><List className="size-4" />Lista</Button></div><p role="status" className="text-xs text-slate-500">{filtered.length} oportunidades visibles · Indicadores globales</p></div>
    {error ? <div role="alert" className="rounded-xl border border-red-100 bg-white p-8 text-center"><p className="text-sm text-red-700">{error}</p><Button className="mt-4" variant="outline" onClick={() => void reload()}>Reintentar</Button></div> : !loaded ? <p role="status" className="p-12 text-center text-sm text-slate-500">Cargando oportunidades...</p> : <>
      {!filtered.length && <div className="rounded-xl border border-slate-200 bg-white p-8 text-center"><GitBranch className="mx-auto mb-3 size-7 text-slate-400" /><h2 className="font-semibold">{items.length ? "Sin oportunidades para estos filtros" : "Todavía no hay oportunidades"}</h2><p className="mt-2 text-sm text-slate-500">{items.length ? "Prueba otra búsqueda o limpia los filtros." : "Crea una oportunidad para un cliente existente."}</p></div>}
      {view === "pipeline" ? <><p className="text-xs text-slate-500">Cambia la etapa desde cada tarjeta. Se guardará al seleccionarla y aplicará la probabilidad sugerida.</p><div role="region" aria-label="Pipeline comercial" tabIndex={0} className="overflow-x-auto rounded-xl pb-4 focus-visible:outline-2 focus-visible:outline-blue-600"><div className="grid grid-flow-col auto-cols-[280px] items-start gap-4">{OPPORTUNITY_STAGES.map((stage) => {
        const column = filtered.filter((item) => item.etapa === stage);
        const total = column.reduce((sum, item) => sum + toCents(item.valor), BigInt(0));
        return <section key={stage} aria-label={`Etapa ${stage}`} className="min-h-48 rounded-xl border border-slate-200 bg-slate-100/70"><div className={`rounded-t-xl border-b p-4 ${stageColors[stage]}`}><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{stage}</h2><span className="rounded-full bg-white/80 px-2 text-xs">{column.length}</span></div><p className="mt-2 text-xs font-medium">{formatCents(total)}</p></div><div className="space-y-3 p-3">{column.length ? column.map((item) => <article key={item.id} aria-label={item.titulo} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="break-words text-sm font-semibold">{item.titulo}</h3><p className="mt-1 truncate text-xs text-slate-500" title={clientName(item.cliente_id)}>{clientName(item.cliente_id)}</p><p className="mt-4 break-words text-lg font-semibold text-slate-900">{formatMoney(item.valor)}</p><div className="mt-3 flex justify-between text-xs text-slate-500"><span>Probabilidad</span><span className="font-medium text-slate-700">{item.probabilidad}%</span></div><div aria-hidden="true" className="mt-1 h-1 rounded bg-slate-100"><div className="h-1 rounded bg-blue-500" style={{ width: `${item.probabilidad}%` }} /></div><p className="mt-3 truncate text-xs text-slate-600" title={ownerName(item.responsable_id)}>{ownerName(item.responsable_id)}</p><p className="mt-1 text-xs text-slate-500">Cierre: {estimatedDate(item.fecha_cierre_estimada)}</p><div className="mt-4 border-t border-slate-100 pt-3"><StageControl item={item} onSaved={saved} /><div className="mt-2 flex justify-end">{actions(item)}</div></div></article>) : <p className="py-6 text-center text-xs text-slate-400">Sin oportunidades</p>}</div></section>;
      })}</div></div></> : Boolean(filtered.length) && <div className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white"><Table><TableHeader><TableRow>{["Oportunidad", "Cliente", "Etapa", "Valor", "Probabilidad", "Responsable", "Fecha estimada", "Acciones"].map((label) => <TableHead key={label} className="px-4 text-xs">{label}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.slice((currentPage - 1) * 10, currentPage * 10).map((item) => <TableRow key={item.id}><TableCell className="max-w-64 truncate px-4 py-4 font-medium" title={item.titulo}>{item.titulo}</TableCell><TableCell className="max-w-48 truncate px-4 text-xs" title={clientName(item.cliente_id)}>{clientName(item.cliente_id)}</TableCell><TableCell className="space-y-2 px-4"><StageBadge stage={item.etapa} /><StageControl item={item} onSaved={saved} /></TableCell><TableCell className="px-4 text-xs font-medium">{formatMoney(item.valor)}</TableCell><TableCell className="px-4 text-xs">{item.probabilidad}%</TableCell><TableCell className="px-4 text-xs">{ownerName(item.responsable_id)}</TableCell><TableCell className="px-4 text-xs">{estimatedDate(item.fecha_cierre_estimada)}</TableCell><TableCell className="px-3">{actions(item)}</TableCell></TableRow>)}</TableBody></Table><div className="flex items-center justify-between gap-3 border-t p-4"><p className="text-xs text-slate-500">Página {currentPage} de {pageCount}</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Anterior</Button><Button size="sm" variant="outline" disabled={currentPage === pageCount} onClick={() => setPage(currentPage + 1)}>Siguiente</Button></div></div></div>}
    </>}<p className="text-xs text-slate-400">Importes en soles · Cambios guardados en Supabase · Ganada y Perdida son etapas cerradas.</p></div>;
}
